### ISSUE TITLE
Commit messages truncated to 56 bytes

### ISSUE THREAD

**Issue by davidfetter** [franckverrot/git_fdw#16] opened 2018-06-10 07:50 UTC
Is this an upstream problem?

**Comment by franckverrot** [comment] 2018-06-10 19:14
I think I gotta stop using those low-levels API once and for all.  Should be fixed, mind confirming?  Thanks a lot for your contributions!

**Closed** 2018-06-10 19:13 UTC

**Comment by davidfetter** [comment] 2018-06-10 19:21
It still breaks like this without #15  ```shackle@[local]:5411/git(11beta1)(27735) # SELECT *, length(message) FROM master.repository LIMIT 100;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
@:/()() > \q
```

**Comment by franckverrot** [comment] 2018-06-11 13:11
Sorry couldn't get to it yesterday.  It's merged now, thanks a ton again!

I couldn't reproduce the bug though, but it was the right thing to do anyways 👍 

Tell me how/if I can help.

**Comment by davidfetter** [comment] 2018-06-11 13:33
Is there some way to test on PostgreSQL 11-to-be? That's what exposed it for me.

**Comment by franckverrot** [comment] 2018-06-11 13:52
If there’s a Ubuntu package for the alpha / beta version it’s totally doable.  We need a new docker config file, and another of those expected_results query (filenames matter).

Tell me if you wanna give it a shot,  i can take a look later tonight.

Thanks!

________________________________

**Comment by davidfetter** [comment] 2018-06-11 14:37
I'll give the docker config a shot. It should be pretty straightforward because you're already using `apt.postgresql.org`.
